spring:
  application:
    name: microservices-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CS_GITHUB_URI}
          username: ${CS_GITHUB_USERNAME}
          password: ${CS_GITHUB_TOKEN}
          
server:
  port: ${CS_PORT:8888}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${RS-USER}:${RS-PASSWORD}@${RS-HOSTNAME:localhost}:${RS-PORT:8761}/eureka/

